/**
 * Vaarn Hypergeometric Codex data (Core Rules > Hypergeometry.md).
 * Equations are the fixed d20 table a codex can hold; Mishaps are rolled on
 * a natural 1 while reading. Effect text uses [INT] as a placeholder for the
 * reader's INT bonus at time of reading — substitute it before display.
 */

export const EQUATIONS = [
  { roll: [1, 3], name: "Antithetical Copy", effect: "Creates a daemonic, insanely evil copy of a target entity. The copy is alive and violently opposed to the existence of the original - if it makes physical contact with the original, both entities are explosively destroyed. The antithesis crumbles to ash after [INT] hours." },
  { roll: [4, 6], name: "Diminish", effect: "The reader or another targeted entity shrinks to half of their original size and mass. This effect lasts [INT] hours." },
  { roll: [7, 9], name: "Erase Paradox", effect: "Targeted Hypergeometric or outsider entity must EGO save vs 10 + [INT]. On failure the entity accepts the fundamental implausibility of their presence and ceases to exist." },
  { roll: [10, 12], name: "Exchange Coordinates", effect: "The reader swaps physical positions with a targeted entity. If a Hypergeometric Mishap is rolled, they become stuck together." },
  { roll: [13, 15], name: "Expand", effect: "The reader or another targeted entity grows to double their original size and mass. This effect lasts [INT] hours." },
  { roll: [16, 18], name: "Flatten", effect: "The reader or another targeted entity is transformed into a 2D hypergeometric entity. This effect lasts [INT] hours.", applies: { effect: "Flatten", text: "Two-dimensional: takes double damage from slashing or slicing weapons.", amount: "INT", unit: "hour", applied: { conditions: ["flat"] } } },
  { roll: [19, 21], name: "Golem", effect: "Imbues an inanimate object with mobility and sentience. It lives for [INT] hours. Make a Reaction Roll to determine its disposition." },
  { roll: [22, 24], name: "Imperfect Copy", effect: "Creates [INT] copies of a target entity. They are colourless and lifeless, resembling sculptures made from ash." },
  { roll: [25, 27], name: "Increase Gravity", effect: "Target entity feels the effects of gravity at ten times the usual force. They are unable to move or fight. This lasts [INT] combat rounds.", applies: { effect: "Increase Gravity", text: "Ten times normal gravity: unable to move or fight.", amount: "INT", unit: "round", viaSave: false } },
  { roll: [28, 30], name: "Invert Gravity", effect: "Target entity has its gravitational polarity reversed for [INT] combat rounds, falling towards the sky. When the effect ends, they take d6 falling damage for each round they fell skywards.", applies: { effect: "Invert Gravity", text: "Falling towards the sky. When it ends, d6 falling damage for each round fallen skywards.", amount: "INT", unit: "round", viaSave: false } },
  { roll: [31, 33], name: "Kinetic Ward", effect: "Creates an invisible wall of hypergeometric force that negates all physical attacks. The barrier can protect one entity for [INT] combat rounds, or [INT] entities for one combat round.", applies: { effect: "Kinetic Ward", text: "A wall of force negates all physical attacks.", amount: "INT", unit: "round", viaSave: false } },
  { roll: [34, 36], name: "Perfect Copy", effect: "Creates a perfect copy of a target entity. The copy resembles the original in all respects. It crumbles to ash after [INT] hours." },
  { roll: [37, 39], name: "Phase", effect: "The reader or another targeted entity is placed out of sync with the material realm. They are visible but cannot touch anything (except other phased entities). This effect lasts [INT] combat rounds.", applies: { effect: "Phase", text: "Out of sync with the material realm: visible, but cannot touch anything except other phased entities.", amount: "INT", unit: "round", viaSave: false } },
  { roll: [40, 42], name: "Portal", effect: "The reader creates a pair of linked portals, which must sit on two flat surfaces that they can see. The portals persist for [INT] combat rounds.", applies: { effect: "Portal", text: "A pair of linked portals persists.", amount: "INT", unit: "round", viaSave: false } },
  { roll: [43, 44], name: "Return Fixed Coordinates", effect: "The reader and/or [INT] other entities are transported to a predetermined point in space. The codex only connects to this pre-written point in space." },
  { roll: [45, 46], name: "Return Random Coordinates", effect: "The reader and/or [INT] other entities are transported to a random point in space which the reader has previously occupied." },
  { roll: [47, 50], name: "Singularity", effect: "Creates a miniature black hole for [INT] combat rounds, drawing in everything in the room. Anything engulfed by the singularity is destroyed. Entities must STR Save vs 10 + [INT] to avoid being drawn into the black hole.", applies: { effect: "Singularity", text: "A miniature black hole draws in everything in the room. Entities STR Save vs 10 + [INT] or are drawn in and destroyed.", amount: "INT", unit: "round", viaSave: false } },
  { roll: [51, 53], name: "Stasis", effect: "A single entity is stranded outside the flow of time for [INT] combat rounds. They cannot be moved, harmed, or interacted with in any way.", applies: { effect: "Stasis", text: "Stranded outside the flow of time: cannot be moved, harmed, or interacted with.", amount: "INT", unit: "round", viaSave: false } },
  { roll: [54, 56], name: "Summon", effect: "The reader plucks a creature from the manifold halls of creation. Roll on the Monster Generator tables to determine the nature and disposition of the entity. Make a Reaction Roll as normal." },
  { roll: [57, 59], name: "Vanish", effect: "The reader or another targeted entity is no longer visible in the normal spectrum of light. Infrared vision will still detect the hidden entity. This effect lasts [INT] hours." },
  { roll: [60, 61], name: "Accelerate", effect: "Target entity moves at double speed for [INT] combat rounds, and makes twice their normal number of attacks.", applies: { effect: "Accelerate", text: "Double speed, and twice the normal number of attacks.", amount: "INT", unit: "round", viaSave: false } },
  { roll: [62, 63], name: "Assert Normality", effect: "Reader sketches out a circle of enforced normality, free of space-time abberations, which lasts for [INT] combat rounds. Hypergeometric and outsider creatures are physically repelled by the drawing of the circle and may not enter it. Mystic Gifts and Exotica that rely on space-time distortions cannot be used inside the circle.", applies: { effect: "Assert Normality", text: "A circle of enforced normality: Hypergeometric and outsider creatures may not enter, and space-time Gifts and Exotica fail inside it.", amount: "INT", unit: "round", viaSave: false } },
  { roll: [64, 65], name: "Attraction", effect: "Target entity attracts objects of the same type, as though powerfully magentised. A glass object attracts and sticks to other glass objects, etc. Lasts for [INT] hours." },
  { roll: [66, 67], name: "Blink", effect: "Reader teleports to a location in line of sight. If a Hypergeometric Mishap is rolled, they become stuck inside a nearby physical object." },
  { roll: [68, 69], name: "Create Cube", effect: "Reader creates a cube, [INT] feet in height and depth, wholly comprised of any material they can currently touch. The cube's slot weight is [INT]." },
  { roll: [70, 71], name: "Darkness", effect: "Reader expells a jet of complete darkness, blinding [INT] creatures for d6 combat rounds. Any light source caught within this jet is permanently extinguished.", applies: { condition: "blind", amount: "1d6", unit: "round" } },
  { roll: [72, 73], name: "Dismantle", effect: "Target entity the caster can touch is separated down into its constituent parts and then grouped according to the caster's whim (by colour, by size, by material, etc.). Living targets must EGO Save vs 10 + [INT] to resist being broken down." },
  { roll: [74, 75], name: "Freeze", effect: "Create a localised supercoolant cloud, dealing [INT] d6 DEX damage to a target. Creatures reduced to 0 DEX are frozen solid and cannot move until thawed.",
    // Hypergeometric Equation Damage to a Target, RULED 2026-09-26 (Matt): the
    // one equation that damages a target directly. [INT]d6 of DEX damage,
    // hypergeometry AND freezing (a supercoolant cloud); 0 DEX is a chat line.
    // Hypergeometry, not the weapon tag's hypergeometric - see attack-properties.js.
    targetDamage: { ability: "dex", count: "INT", die: 6, properties: ["hypergeometry", "freezing"], atZero: "is frozen solid and cannot move until thawed." } },
  { roll: [76, 77], name: "Invert Fate", effect: "Target entity's destiny is inverted. All failed Saves and attack rolls are successes and all successful Saves and attack rolls are failures. This effect lasts [INT] combat rounds.", applies: { effect: "Invert Fate", text: "Destiny inverted: failed Saves and attack rolls succeed, and successful ones fail.", amount: "INT", unit: "round", viaSave: false } },
  { roll: [78, 79], name: "Klein Bottle", effect: "Reader creates a paradoxical hypergeometric bottle, which can contain [INT] doses of any fluid, even those that could not normally be safely transported (magma, acid, sable ikor)." },
  { roll: [80, 81], name: "Labyrinth Seed", effect: "Create a fissure which leads to Vaarn's hypergeometric Labyrinth. Permanent, grows in size over time." },
  { roll: [82, 83], name: "Map of Fate", effect: "Roll [INT]d20. Whenever the reader, or any other PC or NPC, makes a dice roll, they are obliged to choose from these d20 results. Until the pool of d20s is expended, no other dice can be rolled. Using Map of Fate again before these dice are expended results in an immediate Hypergeometric Mishap." },
  { roll: [84, 85], name: "Pale Fire", effect: "Kindle an impossible pale fire, which exclusively burns non-flammable materials. May be extinguished by flammable gases or liquids." },
  { roll: [86, 87], name: "Phantasms", effect: "Create up to [INT] light-distortion anomalies, which may appear to be solid objects or living creatures. They have no weight or depth and do not match the ambient light of their surroundings." },
  { roll: [88, 89], name: "Psychometry", effect: "Reader attunes to the full 4D shape of a held object. They may ask the Referee [INT] Yes or No questions about the object's past, present, and possible futures." },
  { roll: [90, 91], name: "Radiance", effect: "Reader manifests a searing flash of blinding red sunlight. All nearby creatures with eyes must DEX Save vs [INT] rounds of Blindness.", save: { ability: "dex", mode: "resist", vs: "[INT] rounds of Blindness" }, applies: { condition: "blind", amount: "INT", unit: "round" } },
  { roll: [92, 93], name: "Reflective Ward", effect: "Create a hyper-reflective surface the size of a hand-mirror, which can reflect up to [INT] attacks of any type back at the source before breaking. Lasts one combat round.", applies: { effect: "Reflective Ward", text: "A hand-mirror surface reflects up to [INT] attacks back at their source before breaking.", amount: "1", unit: "round", viaSave: false } },
  { roll: [94, 95], name: "Repel", effect: "Target entity repels objects of the same type, as though powerfully anti-magentised. A glass object repels and flies away from other glass objects, etc. Lasts for [INT] hours." },
  { roll: [96, 97], name: "Sever", effect: "The reader severs one of the target's body part from the whole. For the next [INT] hours, the severed part can move separately from its host body, but otherwise operates as normal. Eyes still transmit visual information, hands can grasp, etc." },
  { roll: [98, 100], name: "Web", effect: "Target entity is entangled in a web of hypergeometric threads for [INT] rounds, or [INT] entites are entangled for one round. They lose -5 AV and cannot move.", applies: { condition: "entangled", amount: "INT", unit: "round" } },
];

export const MISHAPS = [
  { name: "Antithesis", effect: "Births a daemonic, insanely evil copy of the reader, with their Level and HP. The copy is violently opposed to the existence of the reader — if it makes physical contact with the reader, both entities are explosively destroyed. The antithetical copy exists for [INT] combat rounds.", applies: { effect: "Antithesis", text: "A daemonic copy of the reader exists. If it touches the reader, both are explosively destroyed. When this ends, the copy is gone.", amount: "INT", unit: "round", viaSave: false } },
  { name: "Brainstorm", effect: "The reader's muddled thoughts are actualised as polychrome lightning, which pours from their eyes and mouth. Everyone nearby takes 2d6 electrical damage, DEX save for half damage." },
  { name: "Chromashadow", effect: "The reader's shadow permanently shifts in hue, becoming pinkish-orange." },
  { name: "Codex Collapse", effect: "The hypergeometric codex collapses in on itself, vanishing from existence." },
  { name: "Entropy-withered", effect: "The reader's body twists and decays under the effect of entropic hypergeometric forces. They lose d6 maximum HP and cannot regain it." },
  { name: "Giant Item", effect: "An item in the reader's inventory is subjected to hypergeometric forces, becoming enormous. The item's weight in slots triples. Roll d10 to determine the slot affected. The change is permanent." },
  { name: "Gigantism", effect: "The reader's body grows uncontrollably in size, swelling to fill the room they are inside. All other occupants must evacuate or be crushed. If this happens outdoors, they continue to grow for the entire duration of this mishap. The growth lasts [INT] hours, followed by a steady deflation." },
  { name: "Inverted Anatomy", effect: "A hypergeometric flux places the reader's internal organs on the outside of their body and their clothing inside. Their AV is 10, and they take doubled damage from all sources. They cannot access any items stored in their inventory slots. This effect lasts [INT] days." },
  { name: "Inverted Fate", effect: "The reader's destiny is inverted. All failed Saves and attack rolls are successes and all successful Saves and attack rolls are failures. This effect lasts [INT] days." },
  { name: "Labyrinth Pox", effect: "The reader contracts Labyrinth Pox, a hypergeometric ailment." },
  { name: "Lost Past", effect: "The reader permanently loses a chunk of their history. The PC loses a single Level, and must subtract d8 HP from their maximum. They must reduce their Ability scores by three points." },
  { name: "Petrified", effect: "The reader's body freezes under the weight of crushing hypergeometric force. The reader is unable to move or act for [INT] hours." },
  { name: "Planeyfied", effect: "The reader becomes a 2D hypergeometric being. Refer to the Planeyfolk ancestry for special rules. This effect lasts [INT] days.", applies: { effect: "Planeyfied", text: "A 2D hypergeometric being, with the Planeyfolk ancestry's special rules. Flat: half damage from bludgeoning attacks, double from slashing or piercing. Attune with Matter: a DEX Save to hold a 3D object, or an hour of quiet concentration to attune one; the items already carried are attuned.", amount: "INT", unit: "day", attuneExisting: true, applied: { conditions: ["flat", "attuneWithMatter"], creatureTypes: ["hypergeometric"] } } },
  { name: "Quantum Daemon", effect: "A paradoxical quantum daemon is called into existence. It is displeased about this and wishes the reader ill." },
  { name: "Revelation", effect: "The reader witnesses a terrible vista in a higher-order dimension, taking d6 damage to INT, PSY, and EGO." },
  { name: "Shrunken Head", effect: "The reader's head is subjected to hypergeometric forces, becoming minute. Their body retains its size. The PC gains a Wound: Shrunken Head. They lose d6 INT, PSY and EGO and cannot wear helmets or hats." },
  { name: "Space-Time Vortex", effect: "A mispronunciation creates a rupture in the fabric of space and time. The vortex vomits forth debris and living creatures. Roll on the local encounter table each combat round. The creature is ejected from the vortex at speed, along with other debris (DEX Save vs 3d8 damage).", applies: { effect: "Space-Time Vortex", text: "A rupture in space and time vomits forth debris and living creatures. Roll on the local encounter table this combat round: the creature is ejected from the vortex at speed, along with other debris (DEX Save vs 3d8 damage).", amount: null, perRound: true, save: { ability: "dex", mode: "resist", vs: "3d8 damage", onFail: { damage: { dice: "3d8" } } } } },
  { name: "Spirit Hand", effect: "The reader's left hand is permanently drawn into a hypergeometric dimension adjacent to our own. Their left arm ends in a strange blue fissure and the missing hand feels as though it is immersed in cold television static. Take d10 DEX damage. Unarmed attacks with the missing hand take on the hypergeometric damage property." },
  { name: "The Yellow Door", effect: "The reader develops a yellow hypergeometric door in their forehead. The door is locked and cannot be opened. The effect is permanent." },
  { name: "Tiny Item", effect: "An item in the reader's inventory is subjected to hypergeometric forces, becoming tiny and totally useless. The item's weight in slots is reduced to nothing. Roll d10 to determine the slot affected. The change is permanent." },
];

/** Replace the [INT] placeholder in effect text with the reader's INT bonus. */
export function substituteINT(effectText, intBonus) {
  return effectText.replaceAll("[INT]", String(intBonus));
}
